# Build Icecast - test
variables:
  BASE_IMAGE_REGISTRY: registry.gitlab.xiph.org/xiph/icecast-docker-images
  DEFAULT_IMAGE: "$BASE_IMAGE_REGISTRY/alpine-icecast-server:20250126210055"
  OSC_IMAGE: "$BASE_IMAGE_REGISTRY/alpine-osc:20250126210022"

default:
  image: "$DEFAULT_IMAGE"
  tags:
      - docker

make_dist:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    LIBIGLOO_PACKAGE_PREFIX: "alpine-libigloo-bins"
    LIBIGLOO_PACKAGE_VERSION: "0.92"
    LIBIGLOO_PROJECT_ID: 143

  stage: build

  script:
    - set -xe # yes i know the scripts will be merged... but for sanities sake
    - cat /etc/os*
    - ./autogen.sh
    - mkdir EXTRA-LIBS
    - export PKG_CONFIG_PATH=`pwd`/EXTRA-LIBS/usr/local/lib/pkgconfig
    # we build these in script as gitlab does not support nested expansion in above variables(or it is not well documented)
    - if echo "$CI_COMMIT_REF_NAME" | grep -- '-with-libigloo$'; then export LIBIGLOO_PACKAGE_SUFFIX=`echo "$CI_COMMIT_REF_NAME" | sed 's/-with-libigloo$//'`; elif echo "$CI_COMMIT_REF_NAME" | grep '^devel'; then export LIBIGLOO_PACKAGE_SUFFIX='devel'; else export LIBIGLOO_PACKAGE_SUFFIX='master'; fi
    - export LIBIGLOO_PACKAGE_BASE=$LIBIGLOO_PACKAGE_PREFIX-$LIBIGLOO_PACKAGE_SUFFIX
    - export LIBIGLOO_PACKAGE_ARCHIVE=$LIBIGLOO_PACKAGE_BASE.tar.gz
    - export LIBIGLOO_PACKAGE_VERSION_WITH_SUFFIX=$LIBIGLOO_PACKAGE_VERSION-$LIBIGLOO_PACKAGE_SUFFIX
    - 'curl -LO --header "JOB-TOKEN: $CI_JOB_TOKEN" "${CI_API_V4_URL}/projects/$LIBIGLOO_PROJECT_ID/packages/generic/$LIBIGLOO_PACKAGE_PREFIX/$LIBIGLOO_PACKAGE_VERSION_WITH_SUFFIX/$LIBIGLOO_PACKAGE_ARCHIVE"'
    - tar -C ./EXTRA-LIBS -xvzf $LIBIGLOO_PACKAGE_ARCHIVE
    - sed -i "s#/usr/local#`pwd`/EXTRA-LIBS/\0#g" `pwd`/EXTRA-LIBS/usr/local/lib/pkgconfig/*.pc
    - grep . `pwd`/EXTRA-LIBS/usr/local/lib/pkgconfig/*.pc
    - ls -la `pwd`/EXTRA-LIBS/usr/local/lib
    - ./configure || cat config.log
    - make
    - make dist
    - tree

    # Tests
    #- su -c "./tests/admin-tests.sh" icecast

  artifacts:
    untracked: true
    expire_in: 1 week

upload_dist:
  image: "$OSC_IMAGE"
  only:
    - master
    - devel
    - devel-stephan48-libigloo-osc

  stage: deploy

  dependencies:
    - make_dist

  before_script:
    - ./ci/osc/prepare-osc-tools.sh

  script:
    - ./ci/osc/handle-osc-upload.sh

upload_dist_release:
  image: "$OSC_IMAGE"
  only:
    - tags

  stage: deploy

  dependencies:
    - make_dist

  before_script:
    - ./ci/osc/prepare-osc-tools.sh

  script:
    - ./ci/osc/handle-osc-upload.sh release
